version: 2
updates:
  # All other deps - monthly
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      # storybook must be done in one-shot upgrades
      - dependency-name: "@storybook*"
      - dependency-name: "storybook"
      - dependency-name: "@chromatic-com/storybook"
      # eslint & prettier also fragile and largely breaking
      - dependency-name: "eslint*"
      - dependency-name: "prettier*"
